resource_group_name = "rg-learning-tf-01"
location            = "uksouth"
vnet_name           = "vnet-learning-tf-01"
subnet_name         = "subnet-learning-tf-01"
nsg_name            = "nsg-learning-tf-01"